import Moondown, { defineMoondownPlugin, type AIStreamHandler, type MoondownTranslations } from '../src';
import logoSrc from '../assets/logo.png';
import { BASIC_PLAYGROUND_DOC, COMPLETE_MARKDOWN_TEST_DOC } from './markdown-fixtures';

type AIPlaygroundMode = 'mock' | 'real';

interface PlaygroundAISettings {
  mode: AIPlaygroundMode;
  locale: string;
  mockChunkSize: number;
  mockDelayMs: number;
  endpoint: string;
  authToken: string;
}

const translations: MoondownTranslations = {
  'moondown.ai.thinking': 'AI is thinking...',
  'moondown.slash.aiContinue': 'AI Continue',
  'moondown.slash.heading1': 'Heading 1',
  'moondown.slash.heading2': 'Heading 2',
  'moondown.slash.heading3': 'Heading 3',
  'moondown.slash.heading4': 'Heading 4',
  'moondown.slash.insertTable': 'Insert Table',
  'moondown.slash.insertLink': 'Insert Link',
  'moondown.slash.quoteBlock': 'Quote Block',
  'moondown.slash.orderedList': 'Ordered List',
  'moondown.slash.unorderedList': 'Unordered List',
  'moondown.slash.codeBlock': 'Code Block',
  'moondown.slash.insertMermaid': 'Insert Mermaid',
  'moondown.slash.insertLatex': 'Insert LaTeX',
  'playground.slash.insertStandupTemplate': 'Insert Standup Template',
  'moondown.prompts.textContinuation': 'Continue writing with consistent style and tone.',
  'moondown.ai.polish.buttons.close': 'Close',
  'moondown.ai.polish.buttons.send': 'Send',
  'moondown.ai.polish.buttons.retry': 'Retry',
  'moondown.ai.polish.buttons.copy': 'Copy',
  'moondown.ai.polish.buttons.copied': 'Copied',
  'moondown.ai.polish.buttons.insert': 'Insert',
  'moondown.ai.polish.placeholder': 'Describe how to polish the selected text...',
  'moondown.ai.polish.hint': 'Press Cmd/Ctrl + Enter to send'
};

const playgroundSlashPlugin = defineMoondownPlugin({
  name: 'playground-slash-plugin',
  slashCommands: [
    {
      id: 'playground.insertStandupTemplate',
      title: 'Insert Standup Template',
      titleKey: 'playground.slash.insertStandupTemplate',
      icon: 'puzzle',
      keywords: ['standup', 'template', 'daily', 'ri bao', 'mo ban', '日报', '模板'],
      execute(view) {
        const position = view.state.selection.main.from;
        view.dispatch({
          changes: {
            from: position,
            insert: [
              '## Standup Update',
              '',
              '- Yesterday:',
              '- Today:',
              '- Blockers:',
              '',
            ].join('\n'),
          },
        });
      },
    },
  ],
});

function parseTag(content: string, tag: string): string {
  const match = content.match(new RegExp(`<${tag}>\\s*([\\s\\S]*?)\\s*</${tag}>`, 'i'));
  return (match?.[1] || '').trim();
}

function normalizeLocale(locale: string): string {
  const normalized = locale.trim();
  return normalized.length > 0 ? normalized : 'en';
}

function normalizeEndpoint(endpoint: string): string {
  const normalized = endpoint.trim();
  return normalized.length > 0 ? normalized : '/__ai_stream';
}

function parsePositiveInt(value: string, fallback: number): number {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) {
    return fallback;
  }
  return parsed;
}

function toStream(
  text: string,
  signal: AbortSignal,
  chunkSize: number,
  delayMs: number
): ReadableStream<string> {
  return new ReadableStream<string>({
    start(controller) {
      let index = 0;
      const timer = window.setInterval(() => {
        if (signal.aborted) {
          window.clearInterval(timer);
          controller.error(new DOMException('Aborted', 'AbortError'));
          return;
        }

        if (index >= text.length) {
          window.clearInterval(timer);
          controller.close();
          return;
        }

        const chunk = text.slice(index, index + chunkSize);
        index += chunkSize;
        controller.enqueue(chunk);
      }, delayMs);

      signal.addEventListener('abort', () => {
        window.clearInterval(timer);
        controller.error(new DOMException('Aborted', 'AbortError'));
      });
    }
  });
}

function createMockAIStream(settings: PlaygroundAISettings): AIStreamHandler {
  const chunkSize = settings.mockChunkSize;
  const delayMs = settings.mockDelayMs;

  return async (_systemPrompt, userPrompt, signal) => {
    if (userPrompt.includes('<text_before_cursor>')) {
      const output = '\n\nThis continuation is generated by the local playground AI mock.';
      return toStream(output, signal, chunkSize, delayMs);
    }

    const sourceText = parseTag(userPrompt, 'source_text');
    const instruction = parseTag(userPrompt, 'user_instruction');
    const normalized = sourceText
      .split('\n')
      .map((line) => line.trimEnd())
      .join('\n')
      .replace(/[ ]{2,}/g, ' ')
      .trim();

    const response = instruction
      ? `${normalized}\n\n(Polished with instruction: ${instruction})`
      : `${normalized}\n\n(Polished by playground mock AI)`;

    return toStream(response, signal, chunkSize, delayMs);
  };
}

function createRealAIStream(settings: PlaygroundAISettings): AIStreamHandler {
  const endpoint = normalizeEndpoint(settings.endpoint);
  const authToken = settings.authToken.trim();

  return async (systemPrompt, userPrompt, signal) => {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (authToken.length > 0) {
      headers.Authorization = `Bearer ${authToken}`;
    }

    const response = await fetch(endpoint, {
      method: 'POST',
      headers,
      body: JSON.stringify({ systemPrompt, userPrompt }),
      signal,
    });

    if (!response.ok || !response.body) {
      const text = await response.text().catch(() => '');
      throw new Error(`AI request failed: ${response.status} ${text}`);
    }

    return new ReadableStream<string>({
      async start(controller) {
        const reader = response.body!.getReader();
        const decoder = new TextDecoder();
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          controller.enqueue(decoder.decode(value, { stream: true }));
        }
        controller.close();
      },
      cancel() {
        try {
          response.body?.cancel();
        } catch {
          // ignore
        }
      },
    });
  };
}

function createAIHandler(settings: PlaygroundAISettings): AIStreamHandler {
  if (settings.mode === 'real') {
    return createRealAIStream(settings);
  }
  return createMockAIStream(settings);
}

function getDefaultAISettings(): PlaygroundAISettings {
  const realAIEnabledByServer = String((window as any).__MOONDOWN_REAL_AI__ || '').toLowerCase() === 'true';
  return {
    mode: realAIEnabledByServer ? 'real' : 'mock',
    locale: 'en',
    mockChunkSize: 18,
    mockDelayMs: 35,
    endpoint: '/__ai_stream',
    authToken: '',
  };
}

const editorContainer = document.querySelector('#editor') as HTMLDivElement;
const brandMark = document.querySelector('.brand-mark') as HTMLImageElement;
const snapshot = document.querySelector('#snapshot') as HTMLPreElement;
const themeState = document.querySelector('#themeState') as HTMLElement;
const syntaxState = document.querySelector('#syntaxState') as HTMLElement;
const readonlyState = document.querySelector('#readonlyState') as HTMLElement;
const accentState = document.querySelector('#accentState') as HTMLElement;
const aiModeState = document.querySelector('#aiModeState') as HTMLElement;
const localeState = document.querySelector('#localeState') as HTMLElement;
const aiEndpointState = document.querySelector('#aiEndpointState') as HTMLElement;

const aiModeSelect = document.querySelector('#aiMode') as HTMLSelectElement;
const localeInput = document.querySelector('#localeInput') as HTMLInputElement;
const aiChunkSizeInput = document.querySelector('#aiChunkSize') as HTMLInputElement;
const aiDelayMsInput = document.querySelector('#aiDelayMs') as HTMLInputElement;
const aiEndpointInput = document.querySelector('#aiEndpoint') as HTMLInputElement;
const aiAuthTokenInput = document.querySelector('#aiAuthToken') as HTMLInputElement;
const toggleThemeInput = document.querySelector('#toggleTheme') as HTMLInputElement;
const toggleSyntaxInput = document.querySelector('#toggleSyntax') as HTMLInputElement;
const toggleReadonlyInput = document.querySelector('#toggleReadonly') as HTMLInputElement;
const accentButtons = Array.from(document.querySelectorAll<HTMLButtonElement>('.accent-dot'));

brandMark.src = logoSrc;

type AccentName = 'blue' | 'graphite' | 'purple' | 'green' | 'orange' | 'pink';

interface AccentPreset {
  label: string;
  hsl: string;
  lightHsl: string;
  darkHsl: string;
}

const ACCENT_PRESETS: Record<AccentName, AccentPreset> = {
  blue: {
    label: 'blue',
    hsl: '211 100% 50%',
    lightHsl: '209 100% 72%',
    darkHsl: '211 100% 42%',
  },
  graphite: {
    label: 'graphite',
    hsl: '240 2% 40%',
    lightHsl: '240 5% 72%',
    darkHsl: '240 3% 28%',
  },
  purple: {
    label: 'purple',
    hsl: '282 85% 58%',
    lightHsl: '282 100% 76%',
    darkHsl: '282 72% 45%',
  },
  green: {
    label: 'green',
    hsl: '142 70% 43%',
    lightHsl: '142 72% 62%',
    darkHsl: '142 76% 34%',
  },
  orange: {
    label: 'orange',
    hsl: '36 100% 50%',
    lightHsl: '36 100% 66%',
    darkHsl: '32 100% 42%',
  },
  pink: {
    label: 'pink',
    hsl: '345 100% 59%',
    lightHsl: '345 100% 72%',
    darkHsl: '345 88% 48%',
  },
};

let theme: 'light' | 'dark' = 'light';
let syntaxHiding = true;
let readOnly = false;
let accent: AccentName = 'blue';
let editorRef: Moondown | null = null;
let aiSettings: PlaygroundAISettings = getDefaultAISettings();

function isAccentName(value: string | undefined): value is AccentName {
  return !!value && value in ACCENT_PRESETS;
}

function applyAccent(nextAccent: AccentName): void {
  accent = nextAccent;
  const preset = ACCENT_PRESETS[nextAccent];
  const rootStyle = document.documentElement.style;
  rootStyle.setProperty('--color-primary-hsl', preset.hsl);
  rootStyle.setProperty('--color-primary-light-hsl', preset.lightHsl);
  rootStyle.setProperty('--color-primary-dark-hsl', preset.darkHsl);
  rootStyle.setProperty('--accent-label', preset.label);
}

function writeAISettingsToControls(settings: PlaygroundAISettings): void {
  aiModeSelect.value = settings.mode;
  localeInput.value = settings.locale;
  aiChunkSizeInput.value = String(settings.mockChunkSize);
  aiDelayMsInput.value = String(settings.mockDelayMs);
  aiEndpointInput.value = settings.endpoint;
  aiAuthTokenInput.value = settings.authToken;
}

function syncAIControls(): void {
  const realMode = aiModeSelect.value === 'real';
  aiChunkSizeInput.disabled = realMode;
  aiDelayMsInput.disabled = realMode;
  aiEndpointInput.disabled = !realMode;
  aiAuthTokenInput.disabled = !realMode;
}

function readAISettingsFromControls(previous: PlaygroundAISettings): PlaygroundAISettings {
  const mode = aiModeSelect.value === 'real' ? 'real' : 'mock';
  return {
    mode,
    locale: normalizeLocale(localeInput.value),
    mockChunkSize: parsePositiveInt(aiChunkSizeInput.value, previous.mockChunkSize),
    mockDelayMs: parsePositiveInt(aiDelayMsInput.value, previous.mockDelayMs),
    endpoint: normalizeEndpoint(aiEndpointInput.value),
    authToken: aiAuthTokenInput.value.trim(),
  };
}

const editor = new Moondown(editorContainer, BASIC_PLAYGROUND_DOC, {
  theme,
  locale: aiSettings.locale,
  syntaxHiding,
  readOnly,
  translations,
  plugins: [playgroundSlashPlugin],
  onAIStream: createAIHandler(aiSettings),
  onChange: () => {
    if (!editorRef) {
      return;
    }
    snapshot.textContent = editorRef.getValue();
  }
});
editorRef = editor;

(window as {
  __MOONDOWN_PLAYGROUND_EDITOR__?: Moondown;
  __MOONDOWN_PLAYGROUND_AI_SETTINGS__?: PlaygroundAISettings;
}).__MOONDOWN_PLAYGROUND_EDITOR__ = editor;

snapshot.textContent = editor.getValue();

function syncStatus(): void {
  themeState.textContent = theme;
  syntaxState.textContent = syntaxHiding ? 'on' : 'off';
  readonlyState.textContent = readOnly ? 'on' : 'off';
  accentState.textContent = ACCENT_PRESETS[accent].label;
  aiModeState.textContent = aiSettings.mode;
  localeState.textContent = aiSettings.locale;
  aiEndpointState.textContent = aiSettings.mode === 'real' ? aiSettings.endpoint : '(mock)';
  setPressedState();
  document.documentElement.dataset.theme = theme;
  document.documentElement.dataset.syntaxHiding = syntaxHiding ? 'on' : 'off';
  document.documentElement.dataset.readonly = readOnly ? 'on' : 'off';
  document.documentElement.dataset.accent = accent;
  for (const button of accentButtons) {
    const isActive = button.dataset.accent === accent;
    button.classList.toggle('is-selected', isActive);
    button.setAttribute('aria-pressed', String(isActive));
  }
  (window as { __MOONDOWN_PLAYGROUND_AI_SETTINGS__?: PlaygroundAISettings }).__MOONDOWN_PLAYGROUND_AI_SETTINGS__ = {
    ...aiSettings,
  };
}

function setPressedState(): void {
  toggleThemeInput.checked = theme === 'dark';
  toggleSyntaxInput.checked = syntaxHiding;
  toggleReadonlyInput.checked = readOnly;
}

function applyAISettings(nextSettings: PlaygroundAISettings): void {
  aiSettings = nextSettings;
  writeAISettingsToControls(aiSettings);
  syncAIControls();
  editor.setLocale(aiSettings.locale);
  editor.setAIStreamHandler(createAIHandler(aiSettings));
  syncStatus();
}

applyAccent(accent);
writeAISettingsToControls(aiSettings);
syncAIControls();
syncStatus();

toggleThemeInput.addEventListener('change', () => {
  theme = toggleThemeInput.checked ? 'dark' : 'light';
  editor.setTheme(theme);
  document.documentElement.classList.toggle('dark', theme === 'dark');
  syncStatus();
});

toggleSyntaxInput.addEventListener('change', () => {
  syntaxHiding = toggleSyntaxInput.checked;
  editor.toggleSyntaxHiding(syntaxHiding);
  syncStatus();
});

toggleReadonlyInput.addEventListener('change', () => {
  readOnly = toggleReadonlyInput.checked;
  editor.setReadOnly(readOnly);
  syncStatus();
});

for (const button of accentButtons) {
  button.addEventListener('click', () => {
    if (!isAccentName(button.dataset.accent)) {
      return;
    }
    applyAccent(button.dataset.accent);
    syncStatus();
  });
}

document.querySelector('#focusEditor')?.addEventListener('click', () => {
  editor.focus();
});

document.querySelector('#replaceContent')?.addEventListener('click', () => {
  editor.setValue(`# New Content\n\n- Timestamp: ${new Date().toISOString()}\n- Theme: ${theme}\n- Readonly: ${String(readOnly)}\n`);
  snapshot.textContent = editor.getValue();
});

document.querySelector('#loadBasicDoc')?.addEventListener('click', () => {
  editor.setValue(BASIC_PLAYGROUND_DOC);
  snapshot.textContent = editor.getValue();
});

document.querySelector('#loadFullDoc')?.addEventListener('click', () => {
  editor.setValue(COMPLETE_MARKDOWN_TEST_DOC);
  snapshot.textContent = editor.getValue();
});

document.querySelector('#logValue')?.addEventListener('click', () => {
  snapshot.textContent = editor.getValue();
});

document.querySelector('#applyAISettings')?.addEventListener('click', () => {
  const nextSettings = readAISettingsFromControls(aiSettings);
  applyAISettings(nextSettings);
});

document.querySelector('#resetAISettings')?.addEventListener('click', () => {
  applyAISettings(getDefaultAISettings());
});

aiModeSelect.addEventListener('change', () => {
  syncAIControls();
});
